export const API_RESPONSE_RECEIVED_WITH_DATA = "API_RESPONSE_RECEIVED_WITH_DATA";
export const API_RESPONSE_RECEIVED_NO_DATA= "API_RESPONSE_RECEIVED_NO_DATA";
export const API_RESPONSE_FAILURE="API_RESPONSE_FAILURE";